### ISSUE TITLE
can not build the cloud

### ISSUE THREAD

**Issue by stormspiritzzz** [kubeedge/kubeedge#1120]
**What happened**:
There are errors when build the cloud.

root@master:~/go/src/github.com/kubeedge/kubeedge# pwd
/root/go/src/github.com/kubeedge/kubeedge
root@master:~/go/src/github.com/kubeedge/kubeedge# make
cd cloud && make
make[1]: Entering directory '/root/go/src/github.com/kubeedge/kubeedge/cloud'
go build -ldflags '-X github.com/kubeedge/kubeedge/pkg/version.buildDate=2019-09-16T04:11:47Z -X github.com/kubeedge/kubeedge/pkg/version.gitCommit=617a8d72af23091264465da7c8ac2b6b46c14897 -X github.com/kubeedge/kubeedge/pkg/version.gitTreeState=clean -X github.com/kubeedge/kubeedge/pkg/version.gitVersion=v1.1.0-beta.0.5+617a8d72af2309 -X github.com/kubeedge/kubeedge/pkg/version.gitMajor=1 -X github.com/kubeedge/kubeedge/pkg/version.gitMinor=1+' cmd/cloudcore/cloudcore.go
 github.com/kubeedge/kubeedge/vendor/k8s.io/component-base/cli/flag
../vendor/k8s.io/component-base/cli/flag/ciphersuites_flag.go:80:18: undefined: tls.VersionTLS13
Makefile:11: recipe for target 'cloudcore' failed
make[1]: *** [cloudcore] Error 2
make[1]: Leaving directory '/root/go/src/github.com/kubeedge/kubeedge/cloud'
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 2

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:v1.0.0
- Hardware configuration:
- OS (e.g. from /etc/os-release):Ubuntu 16.04.6 LTS
- Kernel (e.g. `uname -a`):Linux master 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by subpathdev** [comment]
@stormspiritzzz which go version do you use?

**Comment by stormspiritzzz** [comment]
> @stormspiritzzz which go version do you use?
> (you could use this command to print the version: `go version`)

root@master:~/go/src/github.com/kubeedge/kubeedge# go version
go version go1.11 linux/amd64

**Comment by subpathdev** [comment]
I have to test this on my own system but I think it could be a problem with the go version do you use. How do you download the source code?

**Comment by sids-b** [comment]
@stormspiritzzz , could you try with go version 1.12 as our CI works with go version 1.12

**Comment by subpathdev** [comment]
You are not trying to build v1.0.0 I think you are trying to build the current master and then you have to use go version 1.12

**Comment by kadisi** [comment]
https://github.com/kubeedge/kubeedge/issues/981

please try with go version 1.12

**Comment by subpathdev** [comment]
Seconds ago I have tried to build release 1.0.0 with go version 1.11.13 and it was successfull.

**Comment by sids-b** [comment]
@stormspiritzzz , are you still facing this issue ?

**Comment by NoWhere-zh** [comment]
maybe u can upgrade ur go version

> TLS 1.3 is available on an opt-out basis in Go 1.13. To disable it, set the GODEBUG environment variable (comma-separated key=value options) such that it includes "tls13=0".

ref:https://golang.org/pkg/crypto/tls/
